<<<<<<< HEAD
# Generated by Django 3.0.6 on 2020-05-07 16:25
=======
# Generated by Django 2.1 on 2020-05-07 16:11
>>>>>>> 4cd8a7132e48ec955c5cb6c12052d73669559af0

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
    ]
