# Generated by Django 3.0.6 on 2020-05-07 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['platform']},
        ),
    ]
