# Generated by Django 2.2 on 2020-05-08 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200508_1518'),
        ('product', '0003_product_type'),
    ]

    operations = [
    ]
