# Generated by Django 2.2 on 2020-05-08 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_merge_20200508_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
    ]
