# Generated by Django 3.0.5 on 2020-05-05 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldproduct',
            name='ProductId',
        ),
        migrations.RemoveField(
            model_name='soldproduct',
            name='orderId',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='SoldProduct',
        ),
    ]
