# Generated by Django 2.2 on 2020-05-13 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order_shippingmethod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='productId',
        ),
    ]
