<<<<<<< HEAD
# Generated by Django 3.0.6 on 2020-05-07 16:25
=======
# Generated by Django 2.1 on 2020-05-07 15:30
>>>>>>> 4cd8a7132e48ec955c5cb6c12052d73669559af0

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Zip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searchedItem', models.CharField(max_length=255)),
=======
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=10)),
                ('addressNumber', models.CharField(max_length=20)),
                ('accountImage', models.CharField(max_length=999)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOnCard', models.CharField(max_length=255)),
                ('cardNumber', models.CharField(max_length=255)),
                ('expirationDate', models.CharField(max_length=25)),
                ('CVV', models.FloatField()),
>>>>>>> 4cd8a7132e48ec955c5cb6c12052d73669559af0
                ('accountId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='PaymentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOnCard', models.CharField(max_length=255)),
                ('cardNumber', models.CharField(max_length=255)),
                ('expirationDate', models.DateTimeField()),
                ('CVV', models.FloatField()),
=======
            name='SearchHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searchedItem', models.CharField(max_length=255)),
>>>>>>> 4cd8a7132e48ec955c5cb6c12052d73669559af0
                ('accountId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=10)),
                ('addressNumber', models.CharField(max_length=20)),
                ('accountImage', models.CharField(max_length=999)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAccount.Zip')),
            ],
        ),
=======
            name='Zip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='zip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAccount.Zip'),
        ),
>>>>>>> 4cd8a7132e48ec955c5cb6c12052d73669559af0
    ]
