# Generated by Django 3.0.5 on 2020-05-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinfo',
            name='nameOnCard',
            field=models.CharField(max_length=30),
        ),
    ]
