# Generated by Django 3.0.5 on 2020-05-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAccount', '0002_auto_20200506_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinfo',
            name='cardNumber',
            field=models.CharField(max_length=50),
        ),
    ]
