# Generated by Django 2.1 on 2020-05-07 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAccount', '0004_auto_20200507_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='zip',
            field=models.IntegerField(),
        ),
    ]
