# Generated by Django 2.1 on 2020-05-07 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myAccount', '0006_auto_20200507_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='zip',
        ),
    ]
