# Generated by Django 2.1 on 2020-05-08 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myAccount', '0008_auto_20200508_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='zip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myAccount.Zip'),
        ),
    ]
