# Generated by Django 2.1 on 2020-05-08 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myAccount', '0009_account_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='zip',
            field=models.ForeignKey(default=101, on_delete=django.db.models.deletion.CASCADE, to='myAccount.Zip'),
        ),
    ]
