# Generated by Django 2.2 on 2020-05-08 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myAccount', '0010_auto_20200508_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='accountId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
