# Generated by Django 2.2 on 2020-05-10 13:47

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myAccount', '0011_auto_20200508_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zip',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
