# Generated by Django 2.2 on 2020-05-11 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myAccount', '0013_auto_20200510_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='accountId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='payment', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='accountId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search', to=settings.AUTH_USER_MODEL),
        ),
    ]
