# Generated by Django 2.2 on 2020-05-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAccount', '0016_auto_20200511_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accountImage',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image'),
        ),
    ]
