# Generated by Django 2.2 on 2020-05-11 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myAccount', '0017_auto_20200511_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinfo',
            name='accountId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='payment', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
