# Generated by Django 2.2 on 2020-05-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAccount', '0018_auto_20200511_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinfo',
            name='CVV',
            field=models.IntegerField(),
        ),
    ]
