# Generated by Django 3.0.6 on 2020-05-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAccount', '0020_auto_20200513_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accountImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
