# Generated by Django 2.2 on 2020-05-15 12:00

from django.db import migrations, models
import myAccount.validation.validate


class Migration(migrations.Migration):

    dependencies = [
        ('myAccount', '0021_auto_20200513_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinfo',
            name='CVV',
            field=models.IntegerField(verbose_name=myAccount.validation.validate.validateCVV),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='cardNumber',
            field=models.CharField(max_length=16, verbose_name=myAccount.validation.validate.validateCardNumber),
        ),
    ]
